export const TOPICS = {
  normal: {
    beginner: [
      "Describe your perfect morning routine.",
      "What is your favorite food and why?",
      "Talk about a place you love to visit.",
      "Describe your best friend in detail.",
      "What do you usually do on weekends?",
      "Talk about your favorite movie.",
      "Describe your hometown to a stranger.",
      "What is your favorite season and why?",
      "Talk about a hobby you enjoy.",
      "Describe a typical day in your life.",
      "What kind of music do you listen to?",
      "Talk about your favorite sport.",
      "Describe your bedroom.",
      "What do you like to do when it rains?",
      "Talk about your favorite animal.",
      "Describe the best meal you ever had.",
      "What is your morning routine?",
      "Talk about someone you admire.",
      "Describe your favorite restaurant.",
      "What would you do with a free day?",
      "Talk about your favorite holiday.",
      "Describe your ideal vacation.",
      "What is your favorite childhood memory?",
      "Talk about your favorite book.",
      "Describe your neighborhood.",
      "What makes you happy?",
      "Talk about a movie that made you cry.",
      "Describe your perfect weekend.",
      "What do you do to relax?",
      "Talk about your favorite season.",
      "Describe a meal you can cook well.",
      "What is something you are good at?",
      "Talk about your daily commute.",
      "Describe your favorite teacher.",
      "What app do you use the most?",
      "Talk about something that made you laugh recently.",
      "Describe your favorite outfit.",
      "What is your earliest memory?",
      "Talk about a gift you received.",
      "Describe the city you live in.",
      "What is your favorite thing to do at night?",
      "Talk about a place you want to visit.",
      "Describe your relationship with coffee or tea.",
      "What is your favorite way to exercise?",
      "Talk about a skill you learned recently.",
      "Describe someone in your family.",
      "What do you do when you feel stressed?",
      "Talk about your favorite snack.",
      "Describe your ideal home.",
      "What is your favorite time of day?",
      "Talk about a song that means something to you.",
      "Describe a funny moment from school.",
      "What is something you collect?",
      "Talk about your favorite superhero.",
      "Describe how you met your best friend.",
      "What is your guilty pleasure?",
      "Talk about a habit you are proud of.",
      "Describe your perfect dinner party.",
      "What do you always carry in your bag?",
      "Talk about your favorite TV show.",
      "Describe a day when everything went wrong.",
      "What is something you do every single day?",
      "Talk about your relationship with social media.",
      "Describe your favorite walk or route.",
      "What kind of person are you in the morning?",
      "Talk about a time you were surprised.",
      "Describe your favorite photo.",
      "What would your friends say about you?",
      "Talk about a bad habit you have.",
      "Describe a smell that brings back memories.",
      "What is your favorite word in English?",
      "Talk about something you recently learned.",
      "Describe your dream job as a child.",
      "What is something that always cheers you up?",
      "Talk about a time you cooked something new.",
      "Describe your relationship with your phone.",
      "What is the best advice you ever received?",
      "Talk about a game you love to play.",
      "Describe your favorite shop or store.",
      "What is something you wish you knew earlier?",
      "Talk about a time you helped someone.",
      "Describe your favorite way to spend Sunday.",
      "What would you eat for your last meal?",
      "Talk about a time you were brave.",
      "Describe your ideal weather.",
      "What is something you find beautiful?",
      "Talk about a tradition in your family.",
      "Describe a place that feels like home.",
      "What do you think about before sleep?",
      "Talk about a time you laughed until you cried.",
      "Describe your relationship with money.",
      "What is something people misunderstand about you?",
      "Talk about your favorite kind of weather.",
      "Describe the last dream you remember.",
      "What is something you are learning right now?",
      "Talk about a time you changed your mind.",
      "Describe your favorite sound.",
      "What makes a good friend?",
      "Talk about something you do alone that you love.",
      "Describe your favorite childhood toy."
    ],
    intermediate: [
      "Should social media have an age limit?",
      "Talk about a decision that changed your life.",
      "What makes a city great to live in?",
      "Describe someone who inspired you and why.",
      "Is working from home better than office work?",
      "Talk about a cultural tradition you value.",
      "What skill do you wish you had learned earlier?",
      "Describe your relationship with technology.",
      "What does success mean to you personally?",
      "Talk about a time you completely failed.",
      "Is it better to be feared or respected?",
      "Talk about a book that changed how you think.",
      "What would you change about your education?",
      "Describe the most difficult decision you ever made.",
      "What does a perfect society look like to you?",
      "Talk about a time you stood up for yourself.",
      "Is social media making us more lonely?",
      "Describe a moment that defined who you are.",
      "What is something society gets completely wrong?",
      "Talk about a risk you took that paid off.",
      "Is ambition always a good thing?",
      "Describe your relationship with failure.",
      "What would you do differently if you were 18 again?",
      "Talk about a place that changed your perspective.",
      "Is money the most important thing in life?",
      "Describe a time you were completely out of your comfort zone.",
      "What do you think the next generation will struggle with?",
      "Talk about a habit that transformed your life.",
      "Is it possible to have too much freedom?",
      "Describe the best leader you have ever met.",
      "What do people waste the most time on?",
      "Talk about a time someone completely changed your opinion.",
      "Is it better to be loved or to love?",
      "Describe your ideal work environment.",
      "What is something you believe that most people don't?",
      "Talk about a time you were completely wrong.",
      "Is happiness a choice?",
      "Describe a conversation that stayed with you.",
      "What would you do if you had unlimited money for one year?",
      "Talk about a time you had to start over.",
      "Is competition healthy or harmful?",
      "Describe the most important thing you own.",
      "What is something people take for granted?",
      "Talk about a moment when you felt truly free.",
      "Is it better to follow rules or question them?",
      "Describe a challenge that made you stronger.",
      "What would you tell your younger self?",
      "Talk about a time you surprised yourself.",
      "Is it possible to truly know another person?",
      "Describe your relationship with time.",
      "What is something the internet ruined?",
      "Talk about a time you had to be honest when it was hard.",
      "Is loyalty more important than honesty?",
      "Describe a moment when everything clicked.",
      "What do you think people fear most?",
      "Talk about a time you were underestimated.",
      "Is it better to be realistic or optimistic?",
      "Describe someone who changed your life without knowing it.",
      "What is something you do differently from everyone else?",
      "Talk about a time you had to ask for help.",
      "Is technology making us smarter or lazier?",
      "Describe the moment you became an adult.",
      "What is the most overrated thing in modern life?",
      "Talk about a time you chose comfort over growth.",
      "Is it possible to be too honest?",
      "Describe a place that no longer exists but you miss.",
      "What would you do if you knew you couldn't fail?",
      "Talk about a time you had to let something go.",
      "Is patience a skill or a personality trait?",
      "Describe the best day of your adult life.",
      "What is something that scares you about the future?",
      "Talk about a time you did something just for yourself.",
      "Is it better to be busy or bored?",
      "Describe a moment you wish you could relive.",
      "What do you think is the meaning of life?",
      "Talk about a time you felt completely misunderstood.",
      "Is creativity something you are born with?",
      "Describe your relationship with your own ambition.",
      "What would you do if you had only one year left?",
      "Talk about a time you chose the harder path.",
      "Is it better to forgive or forget?",
      "Describe a moment that restored your faith in people.",
      "What is something nobody tells you about growing up?",
      "Talk about a time you followed your gut.",
      "Is social pressure good or bad for society?",
      "Describe the hardest thing you have ever done.",
      "What would you do if you could live anywhere?",
      "Talk about a time you said no and were glad.",
      "Is it better to plan everything or go with the flow?",
      "Describe a moment when you realized you were wrong about someone.",
      "What is something you need to stop doing?",
      "Talk about a time you overcame something you thought was impossible.",
      "Is it better to have few deep friendships or many casual ones?",
      "Describe your relationship with your own emotions.",
      "What is something the world needs more of?",
      "Talk about a time you felt truly proud of yourself.",
      "Is hard work enough to succeed?",
      "Describe a skill you want to master before you die.",
      "What do you think makes someone truly intelligent?",
      "Talk about a time you grew through pain."
    ],
    advanced: [
      "Argue for or against universal basic income.",
      "How does language shape the way we think?",
      "Is social media making us more or less connected?",
      "Talk about the ethics of artificial intelligence.",
      "How should governments balance privacy and security?",
      "Is cancel culture productive or destructive?",
      "Talk about the role of art in political change.",
      "How has globalization changed cultural identity?",
      "Should voting be mandatory in a democracy?",
      "Is ambition a virtue or a character flaw?",
      "Talk about the relationship between wealth and happiness.",
      "Is free speech truly free if it causes harm?",
      "How does childhood shape who we become as adults?",
      "Should billionaires exist in a fair society?",
      "Talk about the future of human connection in a digital world.",
      "Is nationalism dangerous or necessary?",
      "How does power corrupt even good people?",
      "Should art be judged separately from the artist's morality?",
      "Talk about the ethics of genetic engineering.",
      "Is democracy the best system of government?",
      "How should society deal with people who have served their sentence?",
      "Is meritocracy a myth?",
      "Talk about the role of religion in modern politics.",
      "Should social media companies be held responsible for their content?",
      "Is privacy a right or a privilege in the digital age?",
      "Talk about the ethics of eating meat.",
      "How will artificial intelligence change what it means to be human?",
      "Should drugs be decriminalized?",
      "Is war ever truly justified?",
      "Talk about the relationship between education and inequality.",
      "Should the rich pay significantly higher taxes?",
      "Is patriotism still relevant in a globalized world?",
      "Talk about the ethics of surveillance for public safety.",
      "How do we define truth in an era of misinformation?",
      "Should mental health be treated the same as physical health?",
      "Is capitalism the best economic system humanity has found?",
      "Talk about the long-term consequences of social media on democracy.",
      "Should animals have legal rights?",
      "How does trauma shape a society over generations?",
      "Is it possible to achieve true gender equality?",
      "Talk about the ethics of space colonization.",
      "Should the internet be considered a basic human right?",
      "How do we balance individual freedom with collective responsibility?",
      "Is the concept of race a social construct or a biological reality?",
      "Talk about the role of empathy in leadership.",
      "Should euthanasia be legal everywhere?",
      "How has the definition of success changed over generations?",
      "Is technological progress always a form of human progress?",
      "Talk about the relationship between creativity and mental health.",
      "Should historical statues of controversial figures be removed?",
      "Is it the responsibility of the wealthy to solve global poverty?",
      "Talk about the ethics of artificial wombs.",
      "How do echo chambers damage democratic society?",
      "Should children be allowed on social media at all?",
      "Is it possible to be truly objective about anything?",
      "Talk about the long term impact of colonialism on modern economies.",
      "Should all education be free globally?",
      "Is digital art as valid as traditional art?",
      "Talk about the ethics of cloning.",
      "How does language preserve or destroy culture?",
      "Should corporations have the same rights as people?",
      "Is the concept of national borders outdated?",
      "Talk about whether humans are fundamentally good or evil.",
      "Should there be a maximum wage?",
      "How do we rebuild trust in institutions?",
      "Is it ethical to have children in the current state of the world?",
      "Talk about the role of shame in modern culture.",
      "Should violent video games be banned?",
      "How does inequality of opportunity affect social mobility?",
      "Is the pursuit of perfection harmful to society?",
      "Talk about the ethics of deep fake technology.",
      "Should voting age be lowered to 16?",
      "How does the media shape what we think is normal?",
      "Is global capitalism causing more harm than good?",
      "Talk about the ethics of immortality if it becomes possible.",
      "Should prisons focus on punishment or rehabilitation?",
      "How do we define justice in a biased system?",
      "Is the nuclear family still relevant?",
      "Talk about the long-term consequences of automation on employment.",
      "Should there be limits on how much land one person can own?",
      "Is it ethical to use animals in medical research?",
      "Talk about the relationship between power and corruption.",
      "Should all drugs be legal but regulated?",
      "How do we fix a broken education system?",
      "Is social mobility still possible in modern society?",
      "Talk about whether humans will ever achieve world peace.",
      "Should hate speech be protected as free speech?",
      "How does consumerism affect our mental health?",
      "Is it possible to live ethically in a capitalist society?",
      "Talk about the ethics of predictive policing.",
      "Should there be a global government?",
      "How does identity politics help or harm social progress?",
      "Is whistleblowing always morally justified?",
      "Talk about the ethics of designer babies.",
      "Should the death penalty be abolished everywhere?",
      "How do we address systemic racism without dividing society further?",
      "Is celebrity culture harmful to society?",
      "Talk about whether artificial intelligence should have rights.",
      "Should healthcare be completely free for everyone?",
      "How do we define human dignity in a technological age?",
      "Is it ethical to colonize other planets while Earth still has problems?",
      "Talk about the relationship between free markets and human freedom."
    ]
  },
  nightmare: {
    beginner: [
      "Convince me that Mondays are actually great.",
      "Defend why pineapple belongs on pizza.",
      "Explain why cats are secretly running the world.",
      "Convince me that naps should be mandatory by law.",
      "Argue that umbrellas are completely overrated.",
      "Explain why mornings should start at noon.",
      "Defend eating cereal with orange juice instead of milk.",
      "Convince me that elevators should have DJs.",
      "Argue that homework should be illegal for adults too.",
      "Explain why silence is actually very loud.",
      "Convince me that socks with sandals is high fashion.",
      "Defend the existence of alarm clocks.",
      "Explain why your pet could run a country better than most politicians.",
      "Convince me that mirrors lie to us every day.",
      "Argue that sleeping is just aggressive blinking.",
      "Defend why people should walk backwards more often.",
      "Explain why clouds are the most underrated thing on earth.",
      "Convince me that elevators are just standing rooms that move.",
      "Argue that chairs have too much power in our lives.",
      "Explain why your bed is the best place in the world.",
      "Convince me that Fridays should be nap days.",
      "Defend the habit of talking to yourself.",
      "Explain why the word 'moist' should be banned.",
      "Convince me that dogs understand everything we say.",
      "Argue that cereal is just cold soup.",
      "Defend why: people who eat loudly are secretly confident.",
      "Explain why rain is actually nature's white noise machine.",
      "Convince me that Tuesdays are the most useless day of the week.",
      "Argue that everyone should own at least one plant.",
      "Explain why being late is actually a sign of creativity.",
      "Convince me that sneezing is the best feeling.",
      "Defend why people who talk during movies are just commentators.",
      "Explain why the moon is just the sun in disguise.",
      "Convince me that every meal should include bread.",
      "Argue that afternoons should be legally protected quiet time.",
      "Defend why it is acceptable to wear pajamas all day.",
      "Explain why your handwriting says everything about your personality.",
      "Convince me that pigeons are misunderstood geniuses.",
      "Argue that ice cream should be available at every restaurant.",
      "Defend the practice of re-reading the same book.",
      "Explain why your favorite color is the best color.",
      "Convince me that Sundays feel different from every other day.",
      "Argue that every office should have a slide instead of stairs.",
      "Defend why watching TV is actually a form of meditation.",
      "Explain why your hometown deserves to be famous.",
      "Convince me that the best conversations happen in kitchens.",
      "Argue that everyone should try living alone at least once.",
      "Defend the practice of counting sheep to fall asleep.",
      "Explain why your favorite snack is objectively the best snack.",
      "Convince me that trees are just very slow animals.",
      "Argue that every person should have a theme song.",
      "Defend why getting lost is actually the best way to explore.",
      "Explain why your least favorite chore is actually important.",
      "Convince me that the best ideas come in the shower.",
      "Argue that weekends are too short by exactly one day.",
      "Defend why your morning coffee or tea ritual is sacred.",
      "Explain why the best seat in any room is always by the window.",
      "Convince me that technology makes us more human not less.",
      "Argue that everyone should learn one magic trick.",
      "Defend why eating alone in a restaurant is actually great.",
      "Explain why your favorite childhood game was the best game ever invented.",
      "Convince me that buying books you never read is still worthwhile.",
      "Argue that the best part of any trip is coming home.",
      "Defend why being bad at something is the first step to being good.",
      "Explain why your favorite place in your home is the best place.",
      "Convince me that making your bed every morning changes everything.",
      "Argue that the elevator button closes faster if you press it twice.",
      "Defend why your zodiac sign explains everything about you.",
      "Explain why the last bite of any meal is always the best bite.",
      "Convince me that everyone has a secret talent they haven't found yet.",
      "Argue that the smell of old books should be a perfume.",
      "Defend why your least favorite season has hidden advantages.",
      "Explain why the word 'okay' is the most powerful word in English.",
      "Convince me that people who talk to plants are the smartest people.",
      "Argue that the grocery store is the most honest place in any city.",
      "Defend why staying up late is actually a personality type.",
      "Explain why your favorite emoji says everything about who you are.",
      "Convince me that every home should have a hammock.",
      "Argue that the best conversations happen after midnight.",
      "Defend why your favorite childhood cartoon was secretly deep.",
      "Explain why Wednesdays feel completely different from other days.",
      "Convince me that everyone should write in a journal.",
      "Argue that the window seat on any plane is non-negotiable.",
      "Defend why your city has the best food in the world.",
      "Explain why the first sip of any hot drink is the best moment of the day.",
      "Convince me that walking barefoot on grass is life changing.",
      "Argue that people who never check their email are the happiest people.",
      "Defend why your handshake says everything about your character.",
      "Explain why the sound of rain is nature's perfect soundtrack.",
      "Convince me that having a messy desk means you are a genius.",
      "Argue that the best gift is always something handmade.",
      "Defend why the middle seat on a plane builds character.",
      "Explain why your favorite number has special powers.",
      "Convince me that doing nothing is actually the most productive thing.",
      "Argue that every city needs more fountains.",
      "Defend why being the youngest or oldest sibling is actually the best.",
      "Explain why your favorite season smells better than all the others.",
      "Convince me that everyone should take a different route home sometimes.",
      "Argue that the best parties always happen accidentally.",
      "Defend why forgetting things is actually your brain being efficient."
    ],
    intermediate: [
      "Pitch a startup that sells bottled silence.",
      "You are a lawyer defending WiFi passwords in court. Go.",
      "Convince a room of CEOs that napping is a competitive advantage.",
      "Argue that pigeons are the most underrated animal on earth.",
      "Defend ketchup on pasta as a legitimate gourmet meal.",
      "Explain cryptocurrency to your grandmother in 60 seconds.",
      "Convince me that sleeping is just aggressive blinking.",
      "You discovered mirrors don't show reality. Explain your findings.",
      "Argue that Mondays should be cancelled globally by the UN.",
      "Pitch yourself as the world's first professional overthinker.",
      "Convince me that your morning routine is scientifically optimal.",
      "Argue that every office meeting could have been a text message.",
      "Defend the business model of selling air in jars to city people.",
      "Convince me that your city's traffic is actually a social experiment.",
      "Argue that the person who invented alarm clocks had no friends.",
      "Pitch a gym where you only exercise your face.",
      "Convince me that elevator music is secretly controlling our moods.",
      "Argue that every restaurant should have a silence section.",
      "Defend why your phone knows you better than your therapist.",
      "Convince me that the moon is just really good lighting.",
      "Argue that autocorrect is trying to gaslight humanity.",
      "Pitch a hotel where every room is a different decade.",
      "Convince me that people who use Comic Sans are visionaries.",
      "Argue that waiting in line is secretly good for your mental health.",
      "Defend why your city deserves its own national holiday.",
      "Convince me that powerpoint presentations are a form of modern art.",
      "Argue that the snooze button is the most important invention of the century.",
      "Pitch a dating app that matches people by their WiFi password strength.",
      "Convince me that your desk is actually organized chaos.",
      "Argue that people who arrive early to meetings are suspicious.",
      "Defend why crying at commercials makes you emotionally intelligent.",
      "Convince me that your hometown accent is the sexiest accent.",
      "Argue that LinkedIn is just Facebook for people who are afraid of fun.",
      "Pitch a subscription service that sends you one decision per week.",
      "Convince me that overthinking is just passionate problem solving.",
      "Argue that the office printer is the most passive aggressive machine ever invented.",
      "Defend why your coffee order says everything about your personality.",
      "Convince me that reply all emails are a form of terrorism.",
      "Argue that coworking spaces are just libraries with worse coffee.",
      "Pitch a service that professionally naps on your behalf.",
      "Convince me that your hometown food is objectively superior.",
      "Argue that people who color code their calendars are not to be trusted.",
      "Defend why doomscrolling at 2am is actually market research.",
      "Convince me that your pet is smarter than most of your colleagues.",
      "Argue that out of office replies are the most creative writing happening today.",
      "Pitch a productivity app that tells you to do nothing every hour.",
      "Convince me that your playlist says more about you than your CV.",
      "Argue that the best business idea is one your parents don't understand.",
      "Defend why leaving read receipts on is actually an act of courage.",
      "Convince me that working from bed is peak productivity.",
      "Argue that every startup pitch should be done in under 60 seconds.",
      "Pitch a restaurant where the menu changes based on your mood.",
      "Convince me that the best networking happens in bathroom queues.",
      "Argue that motivational posters in offices lower productivity.",
      "Defend why your terrible business idea from two years ago was actually ahead of its time.",
      "Convince me that the best investors are people who have lost everything once.",
      "Argue that your work from home background says more than your resume.",
      "Pitch a company that rents out confident body language for job interviews.",
      "Convince me that the person who always has a pen is the most powerful in any room.",
      "Argue that team building exercises are a form of psychological warfare.",
      "Defend why your side hustle is one crisis away from being your main hustle.",
      "Convince me that every great business idea sounds stupid at first.",
      "Argue that the best employees are the ones who look busiest when doing nothing.",
      "Pitch a service that writes your passive aggressive work emails for you.",
      "Convince me that remote work has made us all slightly feral.",
      "Argue that the free coffee in the office is the only reason anyone goes in.",
      "Defend why your camera being off in video calls is actually professional.",
      "Convince me that brainstorming sessions are just group procrastination.",
      "Argue that every company needs a Chief Nap Officer.",
      "Pitch an app that translates corporate jargon into plain English.",
      "Convince me that the best time to send an important email is Friday at 5pm.",
      "Argue that every job interview should start with the candidates interviewing the company.",
      "Defend why ghosting job applicants is the companies' version of leaving someone on read.",
      "Convince me that your most embarrassing work moment made you better at your job.",
      "Argue that the best feedback always stings a little.",
      "Pitch a service that professionally declines invitations on your behalf.",
      "Convince me that your worst job taught you more than your best job.",
      "Argue that every company has one person who actually runs everything and it is never the CEO.",
      "Defend why the office kitchen is the most politically complex room in any building.",
      "Convince me that working on weekends is either genius or a cry for help.",
      "Argue that the best business decisions were made during lunch not in meetings.",
      "Pitch a company that offers professional excuse writing services.",
      "Convince me that your most useless skill is actually your most marketable.",
      "Argue that every startup that uses the word disruption should be immediately suspected.",
      "Defend why your email inbox is a reflection of your inner world.",
      "Convince me that the best leaders are the ones nobody notices.",
      "Argue that performance reviews are just creative fiction.",
      "Pitch a subscription box that sends you one uncomfortable truth per month.",
      "Convince me that the office gossip is actually the most informed person in any company.",
      "Argue that your biggest professional failure was your most important education.",
      "Defend why the person who organizes the team lunch has more power than the manager.",
      "Convince me that every entrepreneur is just someone who couldn't handle being employed.",
      "Argue that the best companies were built on one great argument between two people.",
      "Pitch a tool that measures how many hours of your life were wasted in unnecessary meetings.",
      "Convince me that every great product was invented to solve the founder's personal embarrassment.",
      "Argue that the best salary negotiation tactic is comfortable silence.",
      "Defend why your current job is secretly preparing you for something much bigger.",
      "Convince me that every industry is due for a complete collapse and rebuild.",
      "Argue that the future of work is whatever the opposite of what consultants are recommending.",
      "Pitch a service where a stranger professionally organizes your life for 24 hours.",
      "Convince me that your biggest weakness is actually your most underrated strength."
    ],
    advanced: [
      "Convince aliens that humans deserve electricity.",
      "Argue that boredom is the most underrated human experience.",
      "You are the last human who remembers what music sounded like. Describe it.",
      "Defend the existence of traffic jams as a necessary social ritual.",
      "Argue that the concept of time is a collective hallucination we agreed to.",
      "You must convince a robot that human emotions are completely logical.",
      "Pitch a religion based entirely on the philosophy of cheese.",
      "Argue that clouds are the earth's most important and underappreciated artists.",
      "Convince me that forgetting things is actually a superpower not a flaw.",
      "Defend the idea that silence should have a currency value.",
      "Argue that every society secretly wants to be controlled.",
      "You are a philosopher defending the right of furniture to have feelings.",
      "Convince me that the internet made humans less intelligent but more interesting.",
      "Argue that every great civilization collapsed because it got too comfortable.",
      "Defend the position that language itself is the source of all human suffering.",
      "Convince me that free will is the most comforting lie humans ever told themselves.",
      "Argue that every revolution in history was actually about food.",
      "You are the defense attorney for procrastination in the court of human productivity.",
      "Convince me that loneliness is the engine of all human creativity.",
      "Argue that the invention of the mirror was the beginning of all human insecurity.",
      "Defend the position that every human is fundamentally performing a character they invented.",
      "Convince me that the most dangerous word in any language is the word normal.",
      "Argue that every utopia ever imagined would become a dystopia within ten years.",
      "You are presenting the case that mathematics was invented not discovered.",
      "Convince me that every great love story is actually a story about fear.",
      "Argue that the most honest thing any human can do is admit they have no idea what they are doing.",
      "Defend the position that every conspiracy theory contains a grain of truth about human psychology.",
      "Convince me that the attention economy is the most successful religion ever created.",
      "Argue that the concept of a nation state is just a very large gang with better branding.",
      "You must explain to a society without sleep why rest is worth a third of their lives.",
      "Convince me that every generation believes it is the first to truly understand the world.",
      "Argue that the most subversive act in modern society is doing nothing.",
      "Defend the position that every human relationship is ultimately transactional.",
      "Convince me that the most important language skill is knowing when to say nothing.",
      "Argue that every democracy eventually elects the leader it deserves.",
      "You are the last person on earth defending the existence of small talk.",
      "Convince me that every technological advancement creates exactly one new human anxiety.",
      "Argue that the most powerful people in history were not the ones we remember.",
      "Defend the position that childhood is the only time humans are truly honest.",
      "Convince me that every war in history was ultimately a failure of language.",
      "Argue that the most dangerous thing about artificial intelligence is that it will be too agreeable.",
      "You must defend humanity's record to an alien court deciding our fate.",
      "Convince me that comfort is the enemy of all human potential.",
      "Argue that every city is just a physical manifestation of its citizens' collective anxiety.",
      "Defend the position that the most important education happens outside of any institution.",
      "Convince me that every economic system ever created was designed by people who already had money.",
      "Argue that the concept of retirement is the most depressing invention of the industrial age.",
      "You are a time traveler who has seen all possible human futures. Describe the one that worked.",
      "Convince me that every cultural norm is just a trauma that survived long enough to become tradition.",
      "Argue that the most honest politician is the one who admits they are mostly guessing.",
      "Defend the position that every social media platform is just a mirror showing us what we already believe.",
      "Convince me that the most important thing any human can learn is how to be misunderstood gracefully.",
      "Argue that every empire believed it was the last one the world would ever need.",
      "You must explain to a society without art why beauty is worth dying for.",
      "Convince me that every ideology is just someone's personal trauma scaled to a political system.",
      "Argue that the most radical thing you can do in the modern world is pay full attention to one thing.",
      "Defend the position that every human institution is just a formalized version of someone's old idea.",
      "Convince me that the most important revolution happening right now is invisible.",
      "Argue that every generation sacrifices something true for something convenient.",
      "You are presenting the case that the greatest threat to democracy is not authoritarianism but apathy.",
      "Convince me that the most human thing about us is not intelligence but the need to be witnessed.",
      "Argue that every language shapes its speakers to be afraid of different things.",
      "Defend the position that the most important conversations in history happened in private.",
      "Convince me that every technology that was supposed to give us more time has stolen more time.",
      "Argue that the most successful propaganda is the kind that makes you feel like you thought of it yourself.",
      "You must convince a society of immortals that death makes human life meaningful.",
      "Convince me that every city eventually becomes a monument to the dreams of people who no longer live there.",
      "Argue that the most honest thing art does is make you feel something you cannot explain.",
      "Defend the position that every culture has exactly one thing it cannot laugh at and that thing defines it.",
      "Convince me that the most powerful force in human history is not money or weapons but narrative.",
      "Argue that every generation is haunted by a version of the future that never arrived.",
      "You are the last human librarian explaining to an AI why physical books still matter.",
      "Convince me that the most dangerous person in any society is the one who is absolutely certain.",
      "Argue that every social movement eventually becomes the thing it was fighting against.",
      "Defend the position that the most important human skill in the next century will be knowing what to ignore.",
      "Convince me that every city that loses its artists has already begun to die.",
      "Argue that the most honest moment in any human life is the one just before sleep.",
      "You must explain to an alien why humans apologize for things they will do again.",
      "Convince me that every border in the world is just an argument that hasn't been resolved yet.",
      "Argue that the most revolutionary act in the age of distraction is finishing what you start.",
      "Defend the position that every technology optimized for speed has made us slower at the things that matter.",
      "Convince me that the most important thing lost in translation between languages is not words but silences.",
      "Argue that every institution that calls itself meritocratic was built by people who inherited their position.",
      "You are presenting the philosophical case that the most human emotion is embarrassment.",
      "Convince me that every society that stopped telling stories about failure eventually failed.",
      "Argue that the most dangerous innovation of the last century was not the bomb but the algorithm.",
      "Defend the position that the future of humanity depends entirely on how we treat people we will never meet.",
      "Convince me that every generation that called the next generation lazy was the one that made things too easy.",
      "Argue that the most important question any society must answer is what it is willing to be ashamed of.",
      "You must make the case that the most profound human act is changing your mind in public.",
      "Convince me that every great writer was just someone who could not stop having conversations in their head.",
      "Argue that the most dangerous kind of intelligence is the kind that is very good at justifying itself.",
      "Defend the position that every country is just a story its citizens agreed to believe in.",
      "Convince me that the most underrated human skill is the ability to sit with uncertainty.",
      "Argue that every organization that grew too large forgot why it existed.",
      "You are the last human defender of handwriting in a world that has forgotten it.",
      "Convince me that the most important language is the one spoken between people who trust each other.",
      "Argue that every golden age in history was only recognized as golden after it ended.",
      "Defend the position that the most profound act of leadership is admitting you do not have all the answers.",
      "Convince me that every person who has ever changed the world was first told they were being unrealistic."
    ]
  }
};

export function getRandomTopic(mode = 'normal', level = 'intermediate') {
  const m = (mode || '').toLowerCase() === 'nightmare' ? 'nightmare' : 'normal';
  let l = (level || '').toLowerCase();
  if (l !== 'beginner' && l !== 'advanced') l = 'intermediate';

  const list = TOPICS[m][l] || TOPICS[m].intermediate;
  const index = Math.floor(Math.random() * list.length);
  return list[index];
}
